/// The painting traditions an artist picks from when the category is painting -
/// the website's master list (supplied by GalleryZone), searchable by name,
/// region or category.
///
/// Generated from `features/dashboard/painting-art-forms.ts`; keep the order.
class PaintingStyle {
  const PaintingStyle(this.name, this.region, this.category);

  final String name;
  final String region;
  final String category;
}

const paintingStyles = <PaintingStyle>[
  PaintingStyle('Tanjore (Thanjavur) Painting', 'India', 'Classical / Folk'),
  PaintingStyle('Madhubani (Mithila) Art', 'India / Nepal', 'Folk / Tribal'),
  PaintingStyle('Pattachitra', 'India (Odisha/WB)', 'Traditional Scroll'),
  PaintingStyle('Warli Painting', 'India', 'Tribal Art'),
  PaintingStyle('Gond Painting', 'India', 'Tribal Art'),
  PaintingStyle('Kalamkari', 'India', 'Textile / Scroll'),
  PaintingStyle('Pichwai Painting', 'India', 'Devotional Folk'),
  PaintingStyle('Kangra Pahari Painting', 'India', 'Miniature'),
  PaintingStyle('Rajput / Rajasthani Miniature', 'India', 'Court Miniature'),
  PaintingStyle('Mughal Miniature', 'India', 'Court Miniature'),
  PaintingStyle('Cheriyal Scroll Painting', 'India', 'Traditional Scroll'),
  PaintingStyle('Kalighat Painting', 'India', '19th C Folk Modern'),
  PaintingStyle('Bhil Art', 'India', 'Tribal Art'),
  PaintingStyle('Phad Painting', 'India', 'Scroll Painting'),
  PaintingStyle('Mysore Painting', 'India', 'Classical'),
  PaintingStyle('Thangka Painting', 'Tibet / Nepal / Bhutan', 'Sacred Buddhist'),
  PaintingStyle('Paubha', 'Nepal (Newar)', 'Sacred Art'),
  PaintingStyle('Ukiyo-e', 'Japan', 'Woodblock / Painting'),
  PaintingStyle('Nihonga', 'Japan', 'Traditional Japanese'),
  PaintingStyle('Sumi-e (Suibokuga)', 'Japan / China', 'Ink Wash'),
  PaintingStyle('Shanshui', 'China', 'Classical Landscape'),
  PaintingStyle('Gongbi', 'China', 'Court / Realist'),
  PaintingStyle('Minhwa', 'Korea', 'Folk Art'),
  PaintingStyle('Chaekgeori', 'Korea', 'Still Life'),
  PaintingStyle('Tangeh Painting', 'Vietnam', 'Silk Painting'),
  PaintingStyle('Dong Ho Folk Art', 'Vietnam', 'Woodblock Printing'),
  PaintingStyle('Batik Painting', 'Indonesia (Java)', 'Textile / Wax Resist'),
  PaintingStyle('Kamasan Painting', 'Indonesia (Bali)', 'Traditional Scroll'),
  PaintingStyle('Buon Fresco', 'Italy / Mediterranean', 'Architectural Murals'),
  PaintingStyle('Fresco Secco', 'Worldwide', 'Architectural Murals'),
  PaintingStyle('Byzantine Iconography', 'Eastern Mediterranean', 'Sacred Classical'),
  PaintingStyle('Gothic Painting', 'Europe', 'Medieval Classical'),
  PaintingStyle('Renaissance Classicism', 'Italy / Flanders', 'Western Classic'),
  PaintingStyle('Mannerism', 'Europe', '16th C Western'),
  PaintingStyle('Baroque (Chiaroscuro)', 'Europe', '17th C Western'),
  PaintingStyle('Rococo', 'France', '18th C Western'),
  PaintingStyle('Neoclassicism', 'Europe', '18th–19th C Western'),
  PaintingStyle('Romanticism', 'Europe / Americas', '19th C Western'),
  PaintingStyle('Realism', 'France', '19th C Western'),
  PaintingStyle('Pre-Raphaelite Brotherhood', 'UK', '19th C Western'),
  PaintingStyle('Academic Art', 'Europe', '19th C Western'),
  PaintingStyle('Impressionism', 'France', 'Modern Movement'),
  PaintingStyle('Post-Impressionism', 'Europe', 'Modern Movement'),
  PaintingStyle('Pointillism / Divisionism', 'France', 'Modern Movement'),
  PaintingStyle('Fauvism', 'France', 'Modern Movement'),
  PaintingStyle('Expressionism', 'Germany', 'Modern Movement'),
  PaintingStyle('Cubism (Analytic & Synthetic)', 'France / Spain', 'Avant-Garde'),
  PaintingStyle('Futurism', 'Italy', 'Avant-Garde'),
  PaintingStyle('Suprematism', 'Russia', 'Abstract'),
  PaintingStyle('De Stijl (Neoplasticism)', 'Netherlands', 'Abstract'),
  PaintingStyle('Dadaism', 'Switzerland / Europe', 'Avant-Garde / Anti-Art'),
  PaintingStyle('Surrealism', 'Europe', 'Modern Movement'),
  PaintingStyle('Abstract Expressionism', 'USA', 'Modern Abstract'),
  PaintingStyle('Pop Art', 'USA / UK', 'Modern Movement'),
  PaintingStyle('Op Art (Optical Art)', 'Worldwide', 'Modern Movement'),
  PaintingStyle('Minimalism', 'USA', 'Modern Abstract'),
  PaintingStyle('Photorealism / Hyperrealism', 'USA / Europe', 'Modern Realism'),
  PaintingStyle('Art Nouveau Painting', 'Europe', 'Decorative Modern'),
  PaintingStyle('Art Deco Painting', 'Worldwide', 'Decorative Modern'),
  PaintingStyle('Constructivism', 'Russia', 'Avant-Garde'),
  PaintingStyle('Orphism', 'France', 'Abstract'),
  PaintingStyle('Rayonism', 'Russia', 'Abstract'),
  PaintingStyle('Precisionism', 'USA', 'Modern Realism'),
  PaintingStyle('Social Realism', 'Worldwide', 'Political Realism'),
  PaintingStyle('Naïve Art', 'Worldwide', 'Folk Modern'),
  PaintingStyle('Symbolism', 'Europe', '19th C Movement'),
  PaintingStyle('Aboriginal Dot Painting', 'Australia', 'Indigenous Fine Art'),
  PaintingStyle('Aboriginal Bark Painting', 'Australia', 'Indigenous Fine Art'),
  PaintingStyle('Huichol Yarn Painting', 'Mexico', 'Indigenous Folk'),
  PaintingStyle('Native American Sandpainting', 'North America (Navajo)', 'Sacred Ritual Art'),
  PaintingStyle('Native American Ledger Art', 'North America (Plains)', 'Indigenous Narrative'),
  PaintingStyle('Alebrije Painting', 'Mexico', 'Folk Art'),
  PaintingStyle('Retablo Painting', 'Mexico / Latin America', 'Folk Sacred Art'),
  PaintingStyle('Ex-Voto Painting', 'Latin America / Europe', 'Folk Votive'),
  PaintingStyle('Santero Painting', 'Philippines / New Mexico', 'Sacred Folk'),
  PaintingStyle('Persian Miniature', 'Iran', 'Illuminated Fine Art'),
  PaintingStyle('Ottoman Miniature', 'Turkey', 'Court Art'),
  PaintingStyle('Hurufiyya Art', 'Middle East / North Africa', 'Modern Calligraphic'),
  PaintingStyle('Tingatinga', 'Tanzania', 'African Folk'),
  PaintingStyle('Ethiopian Church Murals', 'Ethiopia', 'Sacred Medieval'),
  PaintingStyle('Asante Shrine Murals', 'Ghana', 'Sacred Murals'),
  PaintingStyle('Bogolanfini (Mud Cloth Painting)', 'Mali', 'Textile Art'),
  PaintingStyle('Street Art / Graffiti', 'Worldwide', 'Urban Contemporary'),
  PaintingStyle('Encaustic Painting', 'Ancient / Modern', 'Wax Medium'),
  PaintingStyle('Trompe-l\'œil', 'Worldwide', 'Optical Illusion'),
  PaintingStyle('Reverse Glass Painting (Verre Églomisé)', 'Worldwide', 'Decorative'),
  PaintingStyle('Hard-Edge Painting', 'USA', 'Modern Abstract'),
  PaintingStyle('Color Field Painting', 'USA', 'Modern Abstract'),
  PaintingStyle('Action Painting (Gestural Abstract)', 'USA', 'Modern Abstract'),
  PaintingStyle('Digital Painting', 'Worldwide', 'Digital Medium'),
  PaintingStyle('Mixed Media Collage', 'Worldwide', 'Contemporary'),
  PaintingStyle('Luminism', 'USA', '19th C Landscape'),
  PaintingStyle('Tenebrism', 'Europe', 'Baroque Technique'),
  PaintingStyle('Grisaille', 'Europe', 'Monochrome Technique'),
  PaintingStyle('Sanguine Drawing / Painting', 'Europe', 'Classical Medium'),
  PaintingStyle('Stenciling / Pochoir', 'Worldwide', 'Print/Paint Technique'),
  PaintingStyle('Body Painting', 'Worldwide', 'Body Art'),
];
