// GENERATED from the website's `features/aggregator/aggregator-mou-data.ts` (itself generated from the legal text in
// docs/legal). Do not hand-edit: publish the new text on the website, bump the version
// in the API, and regenerate this file.
//
// The version must match CURRENT_MOU_VERSION.aggregator in backend/packages/db/src/mou.ts -
// the API refuses a signature for any other.

import '../../data/models/mou.dart' show MouParty;
import '../shell/mou/mou_document.dart';

const aggregatorMouVersion = '2026.2';

const aggregatorMou = MouDocument(
  party: MouParty.aggregator,
  version: aggregatorMouVersion,
  title: 'Aggregator Memorandum of Understanding',
  intro: 'Your partner agreement with Galleryzone. Your details are filled in from your profile. Nothing can be reserved until it is signed.',
  footer: 'GalleryZone Private Limited — Aggregator MOU — Revised Final Draft',
  blocks: [
    MouTitle('MEMORANDUM OF UNDERSTANDING'),
    MouHeading('BETWEEN', center: true),
    MouHeading('GALLERYZONE PRIVATE LIMITED', center: true),
    MouParagraph('(Hereinafter referred to as “Galleryzone”, “Company”, or “Platform”)', center: true),
    MouHeading('AND', center: true),
    MouHeading('AUTHORIZED ART PARTNER / AGGREGATOR', center: true),
    MouField('Name', MouFieldKey.partyName),
    MouField('Business Name', MouFieldKey.partyBusinessName),
    MouField('Address', MouFieldKey.partyAddress),
    MouField('GST No.', MouFieldKey.partyGstNo),
    MouField('Mobile No.', MouFieldKey.partyMobile),
    MouField('Effective Date', MouFieldKey.partyEffectiveDate),
    MouParagraph('(Hereinafter referred to as the “Aggregator”)', center: true),
    MouHeading('1. PURPOSE'),
    MouParagraph('1.1 This Memorandum of Understanding (“MOU”) establishes the business relationship between Galleryzone and the Aggregator for the professional display, promotion, facilitation, and sale of artworks and related products through Galleryzone’s aggregator platform.'),
    MouParagraph('1.2 The purpose of this MOU is to define the respective rights, responsibilities, commercial arrangements, inventory custody obligations, pricing mechanism, sales process, incentive structure, and other terms applicable to the relationship between Galleryzone and the Aggregator.'),
    MouParagraph('1.3 The Aggregator shall act solely as an authorized display, promotion, and sales-support partner of Galleryzone and shall conduct its activities in accordance with this MOU and applicable Galleryzone policies.'),
    MouHeading('2. BUSINESS MODEL'),
    MouParagraph('2.1 Galleryzone operates as an art e-commerce platform connecting artists, suppliers, distributors, galleries, Aggregators, and customers through a centralized online platform.'),
    MouParagraph('2.2 The Aggregator shall act as an authorized display and sales-support partner of Galleryzone.'),
    MouParagraph('2.3 The Aggregator shall not be considered the owner of any artwork merely by virtue of receiving, displaying, promoting, or facilitating the sale of such artwork.'),
    MouParagraph('2.4 All customer transactions relating to artworks supplied through this arrangement shall be processed exclusively through the Galleryzone platform unless Galleryzone provides prior written authorization for an alternative arrangement.'),
    MouParagraph('2.5 Nothing in this MOU creates a partnership, joint venture, employment relationship, general agency, or ownership interest between Galleryzone and the Aggregator, except for the limited authorization expressly provided under this MOU.'),
    MouHeading('3. OWNERSHIP OF PRODUCTS AND TRANSFER OF TITLE'),
    MouParagraph('3.1 All artworks and products supplied through Galleryzone shall remain the sole property of the respective Artist until the applicable conditions for transfer of ownership under this Clause are fulfilled.'),
    MouParagraph('3.2 The Aggregator shall have only custody and authorized possession of artworks entrusted to it for display, promotion, or sale facilitation.'),
    MouParagraph('3.3 The Aggregator shall not: (a) claim ownership; (b) sell independently or outside the Galleryzone platform; (c) transfer, assign, pledge, mortgage, or otherwise encumber any artwork; (d) transfer possession to any unauthorized person or entity; or (e) represent itself as the owner.'),
    MouParagraph('3.4 Ownership and title to the physical artwork shall transfer to the customer only upon receipt of the full applicable purchase consideration and successful delivery of the artwork to the customer having been confirmed.'),
    MouParagraph('3.5 Until those conditions are fulfilled, the artwork shall continue to remain the property of the respective Artist.'),
    MouParagraph('3.6 The Aggregator shall immediately notify Galleryzone of any circumstance that may affect ownership, custody, condition, or availability of any artwork.'),
    MouHeading('4. INVENTORY CUSTODY'),
    MouParagraph('4.1 Galleryzone may place artworks or other inventory at the Aggregator’s premises for display and promotional purposes.'),
    MouParagraph('4.2 The Aggregator may also place orders for artworks through the applicable Galleryzone portal or system.'),
    MouParagraph('4.3 Any artwork provided for display shall ordinarily remain with the Aggregator for a maximum period of thirty (30) days unless Galleryzone agrees to an extension in writing.'),
    MouParagraph('4.4 Upon expiry of the applicable display period, or whenever requested by Galleryzone, the Aggregator shall promptly return the artwork to Galleryzone, the Artist, or another location designated by Galleryzone.'),
    MouParagraph('4.5 The Aggregator shall maintain entrusted inventory in a safe, secure, clean and suitable environment; take reasonable precautions against theft, loss, damage, deterioration, misuse and unauthorized access; immediately report incidents; permit reasonable inspections/audits; maintain accurate inventory records; and return inventory immediately upon authorized request.'),
    MouParagraph('4.6 The Aggregator shall be responsible for loss or damage arising from its negligence, wilful misconduct, unauthorized use, misuse, or failure to exercise reasonable care.'),
    MouParagraph('4.7 Inventory records remain subject to Galleryzone’s control and verification.'),
    MouHeading('5. CUSTOMER ORDERS'),
    MouParagraph('5.1 All customer orders relating to artworks covered by this MOU shall be processed exclusively through Galleryzone unless otherwise authorized in writing.'),
    MouParagraph('5.2 Galleryzone shall be responsible for customer invoicing, collection of customer payments, order processing, logistics coordination, customer order communications and applicable post-order processes.'),
    MouParagraph('5.3 The Aggregator may assist customers by providing accurate product information and facilitating communication with Galleryzone.'),
    MouParagraph('5.4 The Aggregator shall not collect customer payments directly unless expressly authorized in writing.'),
    MouParagraph('5.5 The Aggregator shall not make any unauthorized representation, promise, discount, warranty, refund commitment, or other commercial commitment on behalf of Galleryzone.'),
    MouHeading('6. PRICING POLICY'),
    MouParagraph('6.1 “Artist Price” means the price applicable to the artwork as determined by the respective Artist and recorded or communicated to Galleryzone.'),
    MouParagraph('6.2 “Listed Selling Price” means the selling price displayed to the customer through the Galleryzone platform.'),
    MouParagraph('6.3 The Aggregator may, through the applicable Galleryzone system, propose or determine the Listed Selling Price at the permitted stage, subject to Galleryzone’s pricing rules and controls.'),
    MouParagraph('6.4 Galleryzone retains overall control of the pricing framework and may review, approve, modify, restrict or reject any proposed Listed Selling Price.'),
    MouParagraph('6.5 The Aggregator shall not offer unauthorized discounts, modify the Listed Selling Price after an order is placed, represent an unauthorized price, or independently negotiate/conclude a sale outside Galleryzone.'),
    MouParagraph('6.6 Exceptional pricing arrangements require Galleryzone’s prior written approval.'),
    MouHeading('7. SECURITY DEPOSIT, FORFEITURE AND AGGREGATOR LIABILITY'),
    MouParagraph('7.1 Before taking possession of an artwork for display, the Aggregator shall pay an amount equivalent to five percent (5%) of the applicable artwork value as a security deposit/advance, together with applicable delivery, transportation or logistics charges.'),
    MouParagraph('7.2 The security deposit/advance secures the Aggregator’s obligations to properly receive, handle, display, safeguard and return the artwork. It is not a purchase and does not transfer ownership.'),
    MouParagraph('7.3 Upon successful sale, the applicable security deposit may be adjusted or otherwise settled through Galleryzone’s settlement process.'),
    MouParagraph('7.4 If an artwork remains unsold and is returned in the required condition, the security deposit shall be refundable or adjustable, subject to lawful deductions expressly permitted under this MOU.'),
    MouParagraph('7.5 Galleryzone may forfeit the security deposit, in whole or in part, where the Aggregator fails to return an artwork; loses, misplaces or permits unauthorized removal; causes damage through negligence or wilful misconduct; deals with artwork outside the platform without authorization; materially breaches custody/security/handling obligations; refuses inspection/return/reconciliation; abandons artwork; or fails to comply with reasonable instructions.'),
    MouParagraph('7.6 In the event of damage or loss, the deposit may be applied toward reasonable repair, restoration, replacement, recovery, transportation and directly related expenses.'),
    MouParagraph('7.7 The security deposit is security only and shall NOT constitute a maximum liability or liability cap. If loss, theft, destruction or damage attributable to the Aggregator exceeds the deposit, the Aggregator remains liable for the balance properly recoverable under this MOU and applicable law.'),
    MouParagraph('7.8 Where an artwork is lost, stolen, destroyed, or damaged beyond economical repair while in the Aggregator’s custody or control due to circumstances attributable to the Aggregator, and the loss is not fully covered or recovered through applicable insurance or another responsible third party, the Aggregator shall pay Galleryzone an amount equal to the full Artist Price/quoted value of the affected artwork.'),
    MouParagraph('7.9 If insurance coverage is rejected, reduced, invalidated or otherwise fails to compensate the full loss because of an act, omission, negligence, inadequate documentation, failure to comply with insurance requirements, or other conduct attributable to the Aggregator, the Aggregator remains liable for the uninsured or unrecovered portion.'),
    MouParagraph('7.10 In a loss or material damage event attributable to the Aggregator, the security deposit shall not be refundable until the applicable loss and liabilities are fully reconciled. Galleryzone may first apply/forfeit the deposit and then recover any remaining amount.'),
    MouParagraph('7.11 In addition to the Artist Price/quoted value where applicable, the Aggregator shall be responsible, to the extent legally recoverable, for reasonable directly attributable recovery, inspection, restoration, replacement, transportation, insurance-related and legal recovery costs.'),
    MouParagraph('7.12 Where responsibility is shared, liability shall be apportioned according to the actual responsibility established on the available evidence and applicable law.'),
    MouParagraph('7.13 Any forfeiture or deduction shall be communicated with reasonable details of the relevant loss, damage, expense or breach.'),
    MouParagraph('7.14 Delivery, transportation, logistics and handling charges paid by the Aggregator for an unsold artwork shall be non-refundable unless Galleryzone expressly agrees otherwise in writing.'),
    MouHeading('8. TAXES AND REGULATORY COMPLIANCE'),
    MouParagraph('8.1 The final customer-facing Listed Selling Price shall be displayed inclusive of applicable taxes wherever required by law and Galleryzone’s billing system.'),
    MouParagraph('8.2 Galleryzone shall issue customer invoices and collect customer payments in accordance with its billing and tax procedures.'),
    MouParagraph('8.3 Each party shall remain responsible for its own statutory, tax, registration, filing and regulatory obligations.'),
    MouParagraph('8.4 The Aggregator shall maintain registrations, licenses, tax registrations and approvals required for its activities.'),
    MouParagraph('8.5 Nothing transfers one party’s independent statutory obligations to the other.'),
    MouHeading('9. INCENTIVE STRUCTURE AND SETTLEMENT'),
    MouParagraph('9.1 For every successful sale facilitated through the Aggregator, the Aggregator shall be entitled to twenty percent (20%) of the difference between the applicable Listed Selling Price and Artist Price, subject to this MOU.'),
    MouParagraph('9.2 Aggregator Incentive = 20% × (Listed Selling Price − Artist Price).'),
    MouParagraph('9.3 The incentive is calculated only on the eligible difference and not on separately identified taxes, shipping, logistics, insurance or other charges unless expressly agreed.'),
    MouParagraph('9.4 No incentive is payable where there is no positive difference.'),
    MouParagraph('9.5 Any additional commission or commercial benefit must be agreed in writing.'),
    MouParagraph('9.6 Incentive becomes payable only after full customer payment, confirmed successful delivery, and completion of any applicable return/cancellation/cooling-off period.'),
    MouParagraph('9.7 Cancelled, refunded, reversed or otherwise unsuccessful transactions do not generate the corresponding incentive.'),
    MouParagraph('9.8 Final settlement remains subject to lawful deductions, adjustments, taxes, refunds, chargebacks, logistics charges and other amounts recoverable under this MOU.'),
    MouHeading('10. DELIVERY, PACKAGING AND LOGISTICS'),
    MouParagraph('10.1 Delivery shall ordinarily be arranged through Galleryzone’s authorized logistics partners.'),
    MouParagraph('10.2 Galleryzone shall coordinate shipment, applicable logistics, tracking where available, and customer delivery updates.'),
    MouParagraph('10.3 Unless otherwise specified, applicable shipping charges shall be borne by the customer.'),
    MouParagraph('10.4 The Aggregator shall use the same or equivalent packaging, protective materials, framing protection, wrapping and cushioning in which the artwork was received, unless Galleryzone gives different written instructions.'),
    MouParagraph('10.5 Original packaging/protective materials shall not be removed, replaced, altered or discarded without approval except where reasonably necessary for inspection, display or safe transport.'),
    MouParagraph('10.6 Opened packaging shall be properly restored and resealed using equivalent protection.'),
    MouParagraph('10.7 Artwork shall be protected against impact, vibration, moisture, dust, contamination, scratches, frame damage, bending, deformation, breakage and other foreseeable transit risks.'),
    MouParagraph('10.8 Artwork shall be handed to the logistics partner in a condition suitable for safe transportation.'),
    MouParagraph('10.9 If packaging is visibly inadequate or damaged, the Aggregator shall notify Galleryzone and obtain instructions before dispatch.'),
    MouParagraph('10.10 Original documentation, certificates, labels, QR codes, NFC-related materials, display cards and identification materials supplied with artwork shall be securely sent with the artwork where applicable.'),
    MouParagraph('10.11 The Aggregator shall cooperate in timely collection and handover.'),
    MouParagraph('10.12 Unauthorized logistics providers shall not be appointed for Galleryzone orders without written approval.'),
    MouParagraph('10.13 The Aggregator is responsible for loss/damage in its custody caused by negligence, wilful misconduct, improper storage/handling, inadequate packaging, unauthorized packaging alteration, or breach of this MOU.'),
    MouParagraph('10.14 Damage identified before logistics handover must be immediately reported with photographs/evidence and dispatch must await instructions.'),
    MouParagraph('10.15 Reasonable pre-handover photographs/records shall be retained where requested.'),
    MouHeading('11. RESPONSIBILITIES OF THE PARTIES'),
    MouParagraph('11.1 Galleryzone shall be responsible for product sourcing and Artist/supplier coordination, platform-level inventory management, pricing framework, customer billing/invoicing, platform marketing, customer payment collection, settlement, technology maintenance, order processing, logistics coordination and customer transaction communications.'),
    MouParagraph('11.2 The Aggregator shall nominate a Galleryzone Coordinator; display artworks professionally; provide accurate approved information; safeguard inventory; provide reasonable local promotional support; coordinate enquiries/orders; comply with operational/display standards; refrain from unauthorized sales/commitments; and promptly communicate issues.'),
    MouHeading('12. WARRANTY AND AUTHENTICITY'),
    MouParagraph('12.1 Galleryzone shall use reasonable processes to ensure artworks are sourced from genuine Artists or authorized suppliers.'),
    MouParagraph('12.2 The Aggregator shall not provide an independent warranty, authenticity certification, ownership representation or other commitment unless approved by Galleryzone.'),
    MouParagraph('12.3 The Aggregator shall not alter certificates, authenticity information, documentation, labels, QR codes or other identification materials without approval.'),
    MouParagraph('12.4 Complaints regarding authenticity, quality, ownership, warranty, returns, refunds or condition shall be promptly referred to Galleryzone.'),
    MouHeading('13. CONFIDENTIALITY'),
    MouParagraph('13.1 Each Party shall keep confidential non-public commercial, financial, technical, operational, customer, pricing, business, security and proprietary information received from the other Party.'),
    MouParagraph('13.2 Confidential information includes Artist pricing, customer information, supplier information, commercial terms, incentive structures, business plans, operational processes, platform information and non-public financial information.'),
    MouParagraph('13.3 Disclosure is permitted to authorized employees, professional advisers, auditors, insurers, payment processors, logistics providers, contractors and representatives with a legitimate need to know and appropriate confidentiality obligations, or where required by law.'),
    MouParagraph('13.4 Confidentiality does not apply to information already public without breach, lawfully known before disclosure, independently developed, or lawfully received from a third party without confidentiality restriction.'),
    MouParagraph('13.5 These obligations survive termination for so long as information remains confidential or as required by law.'),
    MouHeading('14. INTELLECTUAL PROPERTY'),
    MouParagraph('14.1 Galleryzone’s name, logo, website, software, platform, catalogues, marketing materials, trademarks, designs, content, processes and related intellectual property remain the property of Galleryzone or its licensors.'),
    MouParagraph('14.2 The Aggregator shall not reproduce, modify, distribute, misuse or copy Galleryzone intellectual property, systems or content, or represent ownership, without prior written permission.'),
    MouParagraph('14.3 Authorized promotional/operational use is limited to the purpose and duration authorized.'),
    MouParagraph('14.4 Upon termination, unauthorized use shall cease and materials shall be returned/deleted as reasonably requested.'),
    MouHeading('15. TERM AND RENEWAL'),
    MouParagraph('15.1 This MOU remains valid for an initial period of one (1) year from the Effective Date.'),
    MouParagraph('15.2 It automatically renews for successive periods unless either party gives written notice of non-renewal/termination at least thirty (30) days before expiry.'),
    MouParagraph('15.3 Parties may mutually agree in writing to renew, modify or replace the MOU.'),
    MouParagraph('15.4 Continued relationship after expiry remains subject to this MOU unless superseded by written agreement.'),
    MouHeading('16. TERMINATION, SUSPENSION AND DELISTING'),
    MouParagraph('16.1 Either party may terminate with thirty (30) days’ prior written notice.'),
    MouParagraph('16.2 Galleryzone may terminate immediately for fraud or suspected fraud, material misrepresentation, unauthorized sale/transfer/disposal, damage arising from negligence or wilful misconduct, confidentiality breach, misuse of Galleryzone IP, repeated policy violations, unauthorized pricing/discounting/commitments, failure to return inventory, or any material breach incapable of cure or not cured within the specified period.'),
    MouParagraph('16.3 Upon termination/expiry, the Aggregator shall cease representing itself as authorized, return inventory, cease unauthorized IP use, settle outstanding amounts, provide reconciliation information and cooperate with pending orders.'),
    MouParagraph('16.4 Termination does not affect accrued rights or obligations.'),
    MouParagraph('16.5 Outstanding incentive is payable only if the transaction satisfies Clause 9.'),
    MouParagraph('16.6 Amounts recoverable for loss, damage, unauthorized use or breach may be adjusted against amounts otherwise payable, subject to law.'),
    MouParagraph('16.7 Galleryzone may temporarily suspend, restrict or permanently delist the Aggregator where it fails to comply with a material obligation, requirement, policy, standard or condition under this MOU.'),
    MouParagraph('16.8 Grounds may include custody/handling/return failures; loss, damage, theft or unauthorized removal/transfer; unauthorized sale; unauthorized pricing/discounting; failure to follow procedures; misleading customer information; failure to make required payments/deposits; repeated substantiated customer complaints; materially misleading conduct; serious professional misconduct; or conduct reasonably demonstrated to create a material risk of harm to Galleryzone, Artists, customers, inventory, business operations or brand reputation.'),
    MouParagraph('16.9 A suspension/delisting decision shall be based on a reasonable and bona fide assessment of relevant conduct, evidence, complaint or risk and shall not be exercised arbitrarily or solely on an unsubstantiated allegation.'),
    MouParagraph('16.10 Depending on severity, Galleryzone may issue a warning/compliance notice, suspend platform access, suspend listings/sales, restrict additional inventory, require immediate return, permanently delist, and/or terminate.'),
    MouParagraph('16.11 Where a breach is curable, Galleryzone may provide a reasonable cure period. No cure opportunity is required for fraud, unauthorized sale/transfer, material inventory risk, serious misconduct, IP misuse, or circumstances requiring immediate protective action.'),
    MouParagraph('16.12 Suspension/delisting does not release accrued obligations, including inventory, payment, confidentiality, damage, return and reconciliation obligations.'),
    MouParagraph('16.13 Galleryzone may disable or restrict platform/portal/listing/order/promotional access to the extent reasonably necessary.'),
    MouParagraph('16.14 Delisting does not waive Galleryzone’s right to recover outstanding amounts, loss, damage, costs, liabilities or other remedies.'),
    MouHeading('17. GOVERNING LAW AND JURISDICTION'),
    MouParagraph('17.1 This MOU shall be governed by the laws of India.'),
    MouParagraph('17.2 Subject to the arbitration provisions, competent courts at Hyderabad, Telangana shall have jurisdiction over matters requiring judicial intervention, including interim relief, enforcement of arbitral awards and matters not legally capable of arbitration.'),
    MouHeading('18. DISPUTE RESOLUTION AND ARBITRATION'),
    MouParagraph('18.1 Parties shall first attempt in good faith to resolve disputes through written notice and discussions for thirty (30) days.'),
    MouParagraph('18.2 If unresolved, the dispute shall be finally resolved by arbitration under the Arbitration and Conciliation Act, 1996, as amended.'),
    MouParagraph('18.3 Arbitration shall be conducted by a sole arbitrator mutually appointed. If no agreement is reached within thirty (30) days, appointment shall be made in accordance with applicable law.'),
    MouParagraph('18.4 The seat and legal place of arbitration shall be Hyderabad, Telangana, India. The language shall be English.'),
    MouParagraph('18.5 The award shall be final and binding subject to applicable law.'),
    MouParagraph('18.6 Either party may seek urgent interim/protective/injunctive relief from a competent court. Courts at Hyderabad shall have jurisdiction over such applications and enforcement.'),
    MouParagraph('18.7 Arbitration proceedings and related documents shall be treated as confidential except as required for enforcement, legal compliance or professional advice.'),
    MouHeading('19. FORCE MAJEURE'),
    MouParagraph('19.1 Neither party shall be liable for delay/failure to perform to the extent caused by circumstances beyond reasonable control, including natural disasters, fire, flood, epidemic/pandemic, war, terrorism, civil disturbance, governmental action, strikes, major logistics disruption, widespread telecommunications/internet failure, cyber incidents, utility failure or material third-party infrastructure failure.'),
    MouParagraph('19.2 The affected party shall use reasonable efforts to mitigate the effect and resume performance as soon as practicable.'),
    MouParagraph('19.3 Force majeure shall not excuse payment obligations already due, ownership obligations for artwork already sold, or obligations intended to survive.'),
    MouParagraph('19.4 If the event materially prevents performance for more than sixty (60) consecutive days, either party may request termination of the affected arrangement subject to settlement of accrued rights and obligations.'),
    MouHeading('20. ENTIRE UNDERSTANDING AND AMENDMENTS'),
    MouParagraph('20.1 This MOU constitutes the entire understanding concerning its subject matter and supersedes prior discussions, negotiations, communications and understandings relating to the same subject matter.'),
    MouParagraph('20.2 Amendments, modifications, waivers or variations are valid only when made in writing and accepted by both parties.'),
    MouParagraph('20.3 Amendments may be executed physically or through legally recognized electronic/digital means.'),
    MouParagraph('20.4 If any provision is held invalid, illegal or unenforceable, the remaining provisions continue to the extent permitted by law.'),
    MouParagraph('20.5 Failure or delay in exercising a right does not constitute waiver.'),
    MouParagraph('20.6 This MOU may be executed in counterparts, including electronically, each deemed an original.'),
    MouHeading('21. PERSONAL DATA PROTECTION AND PRIVACY'),
    MouParagraph('21.1 Galleryzone may collect and process the Aggregator’s personal/business data, including identity, contact, address, tax, payment, verification, transaction, inventory, provenance and other information reasonably necessary for onboarding, KYC/verification, listing, sale, settlement, logistics, customer support, fraud prevention, legal compliance, record keeping and legitimate business purposes.'),
    MouParagraph('21.2 Galleryzone shall process such data in accordance with applicable data-protection and privacy laws, including the Digital Personal Data Protection Act, 2023 and applicable rules, as and when applicable.'),
    MouParagraph('21.3 Relevant information may be shared with authorized service providers, payment processors, logistics providers, insurers, Artists, professional advisers, auditors, regulators, tax authorities and other parties where reasonably necessary or legally required.'),
    MouParagraph('21.4 Galleryzone shall take reasonable technical and organizational measures appropriate to the nature of the data.'),
    MouParagraph('21.5 Data may be retained as reasonably necessary for contractual, tax, accounting, fraud-prevention, dispute-resolution, provenance, legal or regulatory requirements.'),
    MouParagraph('21.6 The Aggregator may exercise applicable data rights in accordance with Galleryzone’s privacy policy and applicable law.'),
    MouParagraph('21.7 Galleryzone’s then-current privacy policy and legally required notices form part of the privacy framework, subject to mandatory law.'),
    MouHeading('22. INDEMNIFICATION'),
    MouParagraph('22.1 The Aggregator shall indemnify and hold harmless Galleryzone, its directors, officers, employees and authorized service providers from third-party claims, losses, liabilities, penalties, reasonable costs and expenses arising from or relating to: breach of this MOU; unauthorized sale/transfer or misuse of artwork; loss or damage attributable to the Aggregator; infringement of third-party rights caused by the Aggregator’s acts; false or misleading information/documents supplied by the Aggregator; unlawful conduct attributable to the Aggregator; or taxes/statutory liabilities attributable to the Aggregator’s acts or omissions.'),
    MouParagraph('22.2 Galleryzone remains responsible for liabilities that cannot lawfully be transferred and for loss directly caused by Galleryzone’s proven fraud, wilful misconduct or negligence, subject to this MOU and applicable law.'),
    MouParagraph('22.3 The indemnified party shall, where reasonably practicable, provide notice and reasonable cooperation in defence. No settlement imposing an admission or continuing obligation on the indemnified party shall be entered without its consent, not to be unreasonably withheld.'),
    MouHeading('23. NOTICES'),
    MouParagraph('23.1 Formal notices shall be sent to the email address and/or physical address recorded for the relevant party or subsequently notified in writing.'),
    MouParagraph('23.2 Operational communications may also be made through the Galleryzone platform or official communication channels.'),
    MouParagraph('23.3 Email notice shall be treated as received when transmitted without delivery failure, subject to law. Physical notice shall be treated as received upon delivery or attempted delivery in accordance with law.'),
    MouParagraph('23.4 Each party shall promptly notify changes to contact details.'),
    MouHeading('24. ELECTRONIC EXECUTION AND RECORDS'),
    MouParagraph('24.1 This MOU may be executed and accepted electronically, including electronic signatures, digital signatures, electronic acceptance or other legally valid means.'),
    MouParagraph('24.2 Galleryzone may maintain electronic records of the accepted version, date/time, authentication/verification records and related audit information, subject to law.'),
    MouParagraph('24.3 Electronic copies and records maintained in the ordinary course may be used as evidence of acceptance and execution, subject to law.'),
    MouHeading('25. COMPLIANCE WITH APPLICABLE LAWS'),
    MouParagraph('25.1 Each party shall comply with laws and regulations relevant to its obligations.'),
    MouParagraph('25.2 The Aggregator shall provide accurate KYC, tax, ownership, authorization and other information reasonably required for lawful onboarding and transactions.'),
    MouParagraph('25.3 The Aggregator shall not submit, handle, display or sell artwork or materials that are unlawful, counterfeit, infringing, misleading, fraudulent or otherwise prohibited by applicable law.'),
    MouParagraph('25.4 Galleryzone may suspend, restrict, hold, delist or terminate an artwork/account where reasonably necessary for law, regulatory direction, fraud prevention or material compliance obligations, subject to law.'),
    MouHeading('26. TAX, GST AND STATUTORY DEDUCTIONS'),
    MouParagraph('26.1 Each party is responsible for taxes imposed on it by law in relation to its income, activities and obligations.'),
    MouParagraph('26.2 The Aggregator shall provide accurate GST, PAN, tax residency and other tax information where required.'),
    MouParagraph('26.3 Galleryzone may deduct or withhold amounts required by law, including GST, TDS, TCS or other statutory deductions, and provide relevant records where legally required.'),
    MouParagraph('26.4 Tax treatment may vary by transaction structure, channel, location of supply and applicable law; parties shall cooperate with reasonable documentation.'),
    MouParagraph('26.5 If incorrect tax information supplied by the Aggregator results in additional liability, interest, penalty or loss attributable to that information, the Aggregator shall be responsible to the extent permitted by law.'),
    MouHeading('27. RETURNS, REFUNDS, CANCELLATIONS AND PAYMENT REVERSALS'),
    MouParagraph('27.1 Buyer returns, refunds, cancellations and failed deliveries shall be handled under applicable Galleryzone buyer/return/refund policies and law.'),
    MouParagraph('27.2 For cancelled, refunded, reversed or chargeback transactions, Galleryzone may hold, reverse or adjust the corresponding settlement, including reasonable applicable third-party charges, subject to law.'),
    MouParagraph('27.3 Galleryzone may recover incorrectly paid amounts by adjustment against future amounts, wallet balances or other lawful mechanisms after providing reasonable details.'),
    MouParagraph('27.4 Responsibility for return shipping, return damage, customer-caused damage and other return-related costs shall be determined under applicable transaction terms, insurance, logistics arrangements and law.'),
    MouHeading('28. WALLET AND SETTLEMENT LEDGER'),
    MouParagraph('28.1 Any Galleryzone wallet/account balance is an internal transaction and settlement ledger recording amounts payable, receivable, deductions and adjustments.'),
    MouParagraph('28.2 The wallet is not a deposit, bank account, payment instrument or regulated financial product unless expressly established in accordance with law.'),
    MouParagraph('28.3 Galleryzone may record legitimate deductions, refunds, chargebacks, logistics costs, insurance charges, taxes and other permitted amounts.'),
    MouParagraph('28.4 The Aggregator may raise a written reconciliation query within a reasonable period after receiving a settlement statement.'),
    MouHeading('29. INDEPENDENT RELATIONSHIP; NO PARTNERSHIP OR AGENCY'),
    MouParagraph('29.1 The parties are independent contracting parties. Nothing creates partnership, joint venture, employment or general agency.'),
    MouParagraph('29.2 Neither party may bind the other except where expressly authorized in writing.'),
    MouParagraph('29.3 Galleryzone may act as marketplace, facilitator or authorized intermediary only to the extent described in this MOU, transaction terms or applicable law.'),
    MouHeading('30. THIRD-PARTY SERVICE PROVIDERS AND SUBCONTRACTING'),
    MouParagraph('30.1 Galleryzone may use authorized third-party providers for technology, hosting, verification, KYC, payment processing, logistics, insurance, marketing, customer support, exhibitions, storage and related functions.'),
    MouParagraph('30.2 The Aggregator authorizes Galleryzone to share information reasonably necessary for such services, subject to applicable law.'),
    MouParagraph('30.3 Galleryzone may appoint or change service providers where reasonably necessary for business or compliance purposes.'),
    MouHeading('31. ASSIGNMENT'),
    MouParagraph('31.1 The Aggregator shall not assign or transfer this MOU or material rights without Galleryzone’s prior written consent, except where prohibited by law.'),
    MouParagraph('31.2 Galleryzone may assign or transfer this MOU to an affiliate, successor, purchaser of substantially all relevant business/assets, or other lawful successor, provided the assignment does not unlawfully prejudice accrued rights of the Aggregator.'),
    MouHeading('32. WAIVER; CUMULATIVE REMEDIES'),
    MouParagraph('32.1 Failure or delay in exercising a right or remedy shall not constitute waiver.'),
    MouParagraph('32.2 Rights and remedies under this MOU are cumulative and, subject to law, are in addition to other available rights and remedies.'),
    MouHeading('33. AGGREGATOR CAPACITY AND AUTHORITY'),
    MouParagraph('33.1 The Aggregator represents that it has legal capacity and authority to enter into and perform this MOU.'),
    MouParagraph('33.2 The Aggregator shall not knowingly submit or handle artwork subject to a conflicting ownership, licensing, consignment, security, contractual or other restriction that prevents the activities contemplated by this MOU.'),
    MouParagraph('33.3 Where acting through a representative, entity or authorized person, appropriate authority documentation shall be provided where reasonably required.'),
    MouHeading('34. RISK OF LOSS AND CONDITION'),
    MouParagraph('34.1 Ownership and risk of physical loss/damage are separate concepts. Risk shall be allocated according to the applicable custody, logistics and insurance arrangements.'),
    MouParagraph('34.2 The Aggregator shall disclose known pre-existing damage, defects, restoration, alteration or material condition issues.'),
    MouParagraph('34.3 Galleryzone or an authorized Aggregator may inspect and document condition by photographs, videos or condition reports before dispatch, during custody or before delivery.'),
    MouParagraph('34.4 Parties shall cooperate with logistics providers and insurers in relation to damage or loss.'),
    MouHeading('35. AGGREGATOR CUSTODY, ACCOUNTABILITY AND RECONCILIATION'),
    MouParagraph('35.1 From physical delivery, collection or placement under the Aggregator’s control until confirmed return to Galleryzone, the Artist or an authorized location, the Aggregator shall maintain the artwork in accordance with this MOU.'),
    MouParagraph('35.2 The security deposit shall not be treated as a substitute for custody, safeguarding, return, insurance or financial obligations.'),
    MouParagraph('35.3 The Aggregator shall maintain accurate records of each artwork, including artwork ID, Artist Price, receipt date, condition, location, display status, movement, sale status and return status.'),
    MouParagraph('35.4 Loss, theft, disappearance, damage, unauthorized movement, customer-caused incident, insurance incident or other material event shall be reported immediately.'),
    MouParagraph('35.5 If an artwork cannot be accounted for within the required return period, the Aggregator shall be responsible unless it establishes through reasonable documentary evidence that the loss was caused by circumstances for which it is not legally responsible.'),
    MouParagraph('35.6 Where the Aggregator is responsible for an artwork becoming lost or irrecoverable and the loss is not fully recovered through applicable insurance or another responsible third party, the Aggregator shall pay the full Artist Price/quoted value in accordance with Clause 7, without prejudice to other rights and remedies.'),
    MouParagraph('35.7 Payment for loss or damage does not transfer copyright or other intellectual-property rights in the artwork to the Aggregator.'),
    MouHeading('36. POST-TERMINATION EFFECTS AND RECORD RETENTION'),
    MouParagraph('36.1 Termination does not affect accrued rights or obligations.'),
    MouParagraph('36.2 Galleryzone may retain transaction, tax, accounting, authenticity, provenance, ownership, dispute, fraud-prevention and other records for periods reasonably required by law or legitimate business purposes.'),
    MouParagraph('36.3 Following termination, Galleryzone shall cease new marketing/listing activities where required by applicable withdrawal/termination terms, except for historical records, sold-artwork provenance, transaction records and legally required records.'),
    MouParagraph('36.4 Provisions concerning confidentiality, data protection, intellectual property, payment obligations, indemnity, liability, dispute resolution, record retention and other provisions intended by nature to survive shall survive termination.'),
    MouHeading('37. ORDER OF PRECEDENCE AND POLICIES'),
    MouParagraph('37.1 In case of conflict, the following order applies unless expressly stated otherwise: (a) mandatory applicable law; (b) this signed MOU and signed amendments; (c) transaction-specific written terms accepted by the parties; and (d) applicable operational policies published by Galleryzone.'),
    MouParagraph('37.2 Operational policies may supplement procedures and requirements but shall not materially amend core commercial rights and obligations unless amended in accordance with this MOU or otherwise expressly permitted by law.'),
    MouHeading('38. LANGUAGE AND INTERPRETATION'),
    MouParagraph('38.1 This MOU is executed in English. If a translation is provided for convenience, the English version shall prevail to the extent permitted by law.'),
    MouParagraph('38.2 Headings are for convenience only and shall not affect interpretation.'),
    MouHeading('39. SEVERABILITY'),
    MouParagraph('39.1 If any provision is held invalid, illegal or unenforceable by a competent authority, that provision shall be enforced to the maximum extent permitted by law and the remaining provisions shall continue in force.'),
    MouParagraph('39.2 The parties shall, where reasonably practicable, cooperate to replace an unenforceable provision with a lawful provision that most closely reflects the original commercial intent.'),
    MouHeading('40. LIMITATION OF LIABILITY'),
    MouParagraph('40.1 Except to the extent prohibited by applicable law, neither party shall be liable for indirect, incidental, special or consequential loss arising solely from a remote or unforeseeable event.'),
    MouParagraph('40.2 Nothing in this Clause limits or excludes liability that cannot lawfully be limited or excluded.'),
    MouParagraph('40.3 In particular, nothing in this Clause shall limit the Aggregator’s liability for loss, theft, destruction or damage to artwork attributable to the Aggregator, unauthorized sale or transfer, conversion or misappropriation, fraud, wilful misconduct, gross negligence, breach of confidentiality, infringement caused by the Aggregator, or the Aggregator’s obligation under Clause 7 to pay the full Artist Price/quoted value where the applicable conditions are met.'),
    MouParagraph('40.4 The security deposit is not a liability cap. Any general liability limitation shall not be interpreted to reduce the specific inventory-loss and custody obligations expressly stated in this MOU.'),
    MouHeading('SIGNATURES'),
    MouParagraph('The parties confirm that they have read, understood and agreed to the terms of this MOU and intend to be legally bound by it, subject to applicable law.'),
    MouSigner('FOR GALLERYZONE PRIVATE LIMITED'),
    MouField('Name', MouFieldKey.companyName),
    MouField('Designation', MouFieldKey.companyDesignation),
    MouField('Signature', MouFieldKey.companySignature),
    MouField('Date', MouFieldKey.companyDate),
    MouSigner('FOR AUTHORIZED ART PARTNER / AGGREGATOR'),
    MouField('Name', MouFieldKey.partyName),
    MouField('Business Name', MouFieldKey.partyBusinessName),
    MouField('Signature', MouFieldKey.partySignature),
    MouField('Date', MouFieldKey.partyDate),
    MouNote('LEGAL REVIEW NOTE: This consolidated draft is prepared from the existing Galleryzone Aggregator MOU and the additional provisions requested. It should be reviewed and finalized by Galleryzone’s Indian legal counsel before execution, particularly the provisions concerning arbitration, data protection, tax, indemnification, insurance, liability, electronic execution and enforceability.'),
  ],
);
