// Global Art & Cultural Heritage Index — 100+ Worldwide Painting Art Forms
// Master List (source PDF supplied by GalleryZone). Region and category feed
// the combobox's search as extra keywords, so typing "India" or "Tribal Art"
// surfaces matching styles even when the art form's own name doesn't contain
// the word.
export interface PaintingArtForm {
  name: string;
  region: string;
  category: string;
  description: string;
}

export const PAINTING_ART_FORMS: PaintingArtForm[] = [
  { name: "Tanjore (Thanjavur) Painting", region: "India", category: "Classical / Folk", description: "22k Gold leaf, semi-precious stones, rich relief work on teak wood, depicting Hindu deities." },
  { name: "Madhubani (Mithila) Art", region: "India / Nepal", category: "Folk / Tribal", description: "Geometric line patterns, double borders, natural dyes made from plants and charcoal." },
  { name: "Pattachitra", region: "India (Odisha/WB)", category: "Traditional Scroll", description: "Intricate scroll paintings on treated cloth with natural pigments and bold black outlines." },
  { name: "Warli Painting", region: "India", category: "Tribal Art", description: "Monochromatic white rice paste figures (triangles, circles) on red mud walls showing community life." },
  { name: "Gond Painting", region: "India", category: "Tribal Art", description: "Intricate patterns of dots and lines representing sacred trees, animals, and tribal folklore." },
  { name: "Kalamkari", region: "India", category: "Textile / Scroll", description: "Hand-painted or block-printed cotton fabric art using natural dyes and bamboo pens (kalam)." },
  { name: "Pichwai Painting", region: "India", category: "Devotional Folk", description: "Intricate cloth paintings depicting Lord Krishna (Srinathji), lotus blooms, and cows." },
  { name: "Kangra Pahari Painting", region: "India", category: "Miniature", description: "Delicate lyricism, soft natural colors, and poetic depictions of Radha-Krishna love stories." },
  { name: "Rajput / Rajasthani Miniature", region: "India", category: "Court Miniature", description: "Vivid colors, bold profile portraiture, court processions, and Ragamala series." },
  { name: "Mughal Miniature", region: "India", category: "Court Miniature", description: "Blend of Persian, Islamic, and Indian styles detailing royal courts, flora, fauna, and hunts." },
  { name: "Cheriyal Scroll Painting", region: "India", category: "Traditional Scroll", description: "Stylized narrative film-strip style scrolls depicting local folk legends on khadi canvas." },
  { name: "Kalighat Painting", region: "India", category: "19th C Folk Modern", description: "Bold, sweeping brushstrokes on paper depicting social satire, religious icons, and daily life." },
  { name: "Bhil Art", region: "India", category: "Tribal Art", description: "Vivid color fields covered in uniform patterns of dots representing ancestral spirits." },
  { name: "Phad Painting", region: "India", category: "Scroll Painting", description: "Long narrative cloth scrolls depicting local deity-heroes (Pabu-ji, Dev-narayan)." },
  { name: "Mysore Painting", region: "India", category: "Classical", description: "Gesso work, delicate gold leaf work, muted colors, and serene depictions of gods." },
  { name: "Thangka Painting", region: "Tibet / Nepal / Bhutan", category: "Sacred Buddhist", description: "Intricate silk embroidery or painted scrolls depicting Buddhist deities and mandalas." },
  { name: "Paubha", region: "Nepal (Newar)", category: "Sacred Art", description: "Traditional Newari religious paintings of Buddhist and Hindu deities using mineral pigments." },
  { name: "Ukiyo-e", region: "Japan", category: "Woodblock / Painting", description: "'Pictures of the floating world' featuring actors, landscapes, flora, and urban life." },
  { name: "Nihonga", region: "Japan", category: "Traditional Japanese", description: "Traditional Japanese painting using natural mineral pigments, shell powder, and gold leaf." },
  { name: "Sumi-e (Suibokuga)", region: "Japan / China", category: "Ink Wash", description: "Zen-inspired black ink brushwork emphasizing minimalism, rhythm, and empty space." },
  { name: "Shanshui", region: "China", category: "Classical Landscape", description: "'Mountain-Water' landscape brush painting capturing spiritual essence over realism." },
  { name: "Gongbi", region: "China", category: "Court / Realist", description: "Meticulous detail and precise brushstrokes depicting court portraits, birds, and flowers." },
  { name: "Minhwa", region: "Korea", category: "Folk Art", description: "Vivid traditional Korean folk painting depicting animals, symbols of longevity, and humor." },
  { name: "Chaekgeori", region: "Korea", category: "Still Life", description: "Korean still-life painting genre featuring books, ceramics, and scholar accessories." },
  { name: "Tangeh Painting", region: "Vietnam", category: "Silk Painting", description: "Delicate transparent watercolors layered over silk fabric capturing countryside life." },
  { name: "Dong Ho Folk Art", region: "Vietnam", category: "Woodblock Printing", description: "Traditional woodblock printing on zho paper using natural colors from shell powder." },
  { name: "Batik Painting", region: "Indonesia (Java)", category: "Textile / Wax Resist", description: "Wax-resist dyeing and painting technique creating intricate traditional motifs on cloth." },
  { name: "Kamasan Painting", region: "Indonesia (Bali)", category: "Traditional Scroll", description: "Classical Balinese narrative style derived from wayang puppet theatre and Ramayana epics." },
  { name: "Buon Fresco", region: "Italy / Mediterranean", category: "Architectural Murals", description: "Painting directly into fresh wet lime plaster, fusing pigment permanently with walls." },
  { name: "Fresco Secco", region: "Worldwide", category: "Architectural Murals", description: "Painting pigments mixed with organic binders on dried lime plaster walls." },
  { name: "Byzantine Iconography", region: "Eastern Mediterranean", category: "Sacred Classical", description: "Highly stylized, flat symbolic religious icons with brilliant gold leaf backgrounds." },
  { name: "Gothic Painting", region: "Europe", category: "Medieval Classical", description: "Elongated figures, international gothic elegance, and illuminated manuscripts." },
  { name: "Renaissance Classicism", region: "Italy / Flanders", category: "Western Classic", description: "Linear perspective, sfumato blending, anatomical realism, and humanism." },
  { name: "Mannerism", region: "Europe", category: "16th C Western", description: "Elongated proportions, artificial elegance, complex poses, and vivid surreal color palettes." },
  { name: "Baroque (Chiaroscuro)", region: "Europe", category: "17th C Western", description: "Dramatic theatrical lighting, extreme shadow contrast (tenebrism), and high emotion." },
  { name: "Rococo", region: "France", category: "18th C Western", description: "Pastel tones, playful romantic themes, asymmetrical scrolling ornament, and ornate frivolity." },
  { name: "Neoclassicism", region: "Europe", category: "18th–19th C Western", description: "Heroic simplicity, symmetrical composition, smooth brushwork inspired by Ancient Rome." },
  { name: "Romanticism", region: "Europe / Americas", category: "19th C Western", description: "Emphasis on emotion, individualism, stormy sublime nature, and dramatic historical events." },
  { name: "Realism", region: "France", category: "19th C Western", description: "Depicting everyday working-class life accurately without idealization or romantic drama." },
  { name: "Pre-Raphaelite Brotherhood", region: "UK", category: "19th C Western", description: "Vibrant jewel tones, precise detail, nature-focused realism, and medieval literary subjects." },
  { name: "Academic Art", region: "Europe", category: "19th C Western", description: "High-finish classical historical and mythological works governed by official art academies." },
  { name: "Impressionism", region: "France", category: "Modern Movement", description: "Short, thick brushstrokes capturing optical effects of light and atmosphere En Plein Air." },
  { name: "Post-Impressionism", region: "Europe", category: "Modern Movement", description: "Emotional color expression, structural forms, and symbolic content (Van Gogh, Cezanne)." },
  { name: "Pointillism / Divisionism", region: "France", category: "Modern Movement", description: "Applying tiny distinct dots of pure color that visually blend in the viewer's eye." },
  { name: "Fauvism", region: "France", category: "Modern Movement", description: "Wild, non-naturalistic explosive colors and direct, simplified brushwork (Matisse)." },
  { name: "Expressionism", region: "Germany", category: "Modern Movement", description: "Distorted forms and intense subjective emotional states (Die Brücke, Der Blaue Reiter)." },
  { name: "Cubism (Analytic & Synthetic)", region: "France / Spain", category: "Avant-Garde", description: "Deconstruction of 3D objects into multi-perspective geometric facets." },
  { name: "Futurism", region: "Italy", category: "Avant-Garde", description: "Capturing dynamic speed, mechanical movement, technological energy, and modern urbanism." },
  { name: "Suprematism", region: "Russia", category: "Abstract", description: "Pure abstract geometric shapes (squares, circles) painted in limited monochromatic colors." },
  { name: "De Stijl (Neoplasticism)", region: "Netherlands", category: "Abstract", description: "Primary colors (red, blue, yellow) bounded by straight black vertical/horizontal grids." },
  { name: "Dadaism", region: "Switzerland / Europe", category: "Avant-Garde / Anti-Art", description: "Absurdist collages, photomontages, and readymade compositions challenging aesthetics." },
  { name: "Surrealism", region: "Europe", category: "Modern Movement", description: "Unconscious dreamscapes, illogical juxtapositions, and hyper-realistic illusionism." },
  { name: "Abstract Expressionism", region: "USA", category: "Modern Abstract", description: "Spontaneous gestural action painting (Pollock) and deep spiritual Color Field fields (Rothko)." },
  { name: "Pop Art", region: "USA / UK", category: "Modern Movement", description: "Mass culture imagery, comic strips, bold outlines, commercial screen-printing aesthetics." },
  { name: "Op Art (Optical Art)", region: "Worldwide", category: "Modern Movement", description: "Abstract geometric patterns creating optical illusions of movement or vibration." },
  { name: "Minimalism", region: "USA", category: "Modern Abstract", description: "Extreme reduction of form to basic geometric shapes and flat monochromatic surfaces." },
  { name: "Photorealism / Hyperrealism", region: "USA / Europe", category: "Modern Realism", description: "Painstaking reproduction of photographic detail with extreme clarity and precision." },
  { name: "Art Nouveau Painting", region: "Europe", category: "Decorative Modern", description: "Sinuous, flowing organic lines inspired by plants, vines, and elegant feminine forms." },
  { name: "Art Deco Painting", region: "Worldwide", category: "Decorative Modern", description: "Sleek geometric symmetry, bold streamlined shapes, and metallic luxury embellishments." },
  { name: "Constructivism", region: "Russia", category: "Avant-Garde", description: "Industrial, geometric, propaganda-driven aesthetic fusing graphic design and art." },
  { name: "Orphism", region: "France", category: "Abstract", description: "Offshoot of Cubism focusing on lyrical abstract color harmonies and luminous circles." },
  { name: "Rayonism", region: "Russia", category: "Abstract", description: "Abstract depiction of dynamic light rays reflecting off objects in space." },
  { name: "Precisionism", region: "USA", category: "Modern Realism", description: "Sharply defined, sleek mechanical landscapes and industrial architecture." },
  { name: "Social Realism", region: "Worldwide", category: "Political Realism", description: "Realistic art focused on working-class struggles, poverty, and political commentary." },
  { name: "Naïve Art", region: "Worldwide", category: "Folk Modern", description: "Childlike simplicity, flat perspective, bright colors, and intuitive composition." },
  { name: "Symbolism", region: "Europe", category: "19th C Movement", description: "Mystical, dreamlike, and esoteric imagery expressing internal psychological states." },
  { name: "Aboriginal Dot Painting", region: "Australia", category: "Indigenous Fine Art", description: "Intricate dot patterns mapping sacred Dreamtime stories, topography, and secret symbols." },
  { name: "Aboriginal Bark Painting", region: "Australia", category: "Indigenous Fine Art", description: "Natural ochre paintings executed on stripped tree bark depicting ancestral spirits." },
  { name: "Huichol Yarn Painting", region: "Mexico", category: "Indigenous Folk", description: "Pressed colorful yarn on wax boards illustrating shamanic peyote visions and deities." },
  { name: "Native American Sandpainting", region: "North America (Navajo)", category: "Sacred Ritual Art", description: "Dry paintings made with colored sands for sacred healing ceremonies." },
  { name: "Native American Ledger Art", region: "North America (Plains)", category: "Indigenous Narrative", description: "Narrative drawings made on recycled ledger paper depicting horse raids and battles." },
  { name: "Alebrije Painting", region: "Mexico", category: "Folk Art", description: "Vividly painted fantastical wooden sculptures of hybrid mythical creatures." },
  { name: "Retablo Painting", region: "Mexico / Latin America", category: "Folk Sacred Art", description: "Small devotional oil paintings on tin or wood depicting saints and miraculous events." },
  { name: "Ex-Voto Painting", region: "Latin America / Europe", category: "Folk Votive", description: "Votive narrative paintings offering public thanks to saints for miraculous survival." },
  { name: "Santero Painting", region: "Philippines / New Mexico", category: "Sacred Folk", description: "Traditional painting and carving of devotional holy icons and saints." },
  { name: "Persian Miniature", region: "Iran", category: "Illuminated Fine Art", description: "Intricate court scenes, lapis lazuli blues, gold leaf gilding, and poetic narratives." },
  { name: "Ottoman Miniature", region: "Turkey", category: "Court Art", description: "Bold flat color blocks, realistic topographical maps, and imperial historical records." },
  { name: "Hurufiyya Art", region: "Middle East / North Africa", category: "Modern Calligraphic", description: "Fusion of traditional Arabic letterforms with modern abstract painting." },
  { name: "Tingatinga", region: "Tanzania", category: "African Folk", description: "Vibrant, high-gloss enamel depictions of African safari animals and folklore." },
  { name: "Ethiopian Church Murals", region: "Ethiopia", category: "Sacred Medieval", description: "Distinct large-eyed Christian figures painted on church walls and parchment." },
  { name: "Asante Shrine Murals", region: "Ghana", category: "Sacred Murals", description: "Geometric wall paintings on clay shrines honoring traditional West African deities." },
  { name: "Bogolanfini (Mud Cloth Painting)", region: "Mali", category: "Textile Art", description: "Fermented river mud painted directly onto woven cotton fabric creating abstract symbols." },
  { name: "Street Art / Graffiti", region: "Worldwide", category: "Urban Contemporary", description: "Spray paint art, stencils, wheatpastes, and large-scale architectural murals." },
  { name: "Encaustic Painting", region: "Ancient / Modern", category: "Wax Medium", description: "Pigments mixed with hot melted beeswax and damar resin burned into surfaces." },
  { name: "Trompe-l'œil", region: "Worldwide", category: "Optical Illusion", description: "Hyper-realistic painting technique that deceives the viewer's eye into seeing 3D space." },
  { name: "Reverse Glass Painting (Verre Églomisé)", region: "Worldwide", category: "Decorative", description: "Applying paint to the back of a glass panel to be viewed from the front." },
  { name: "Hard-Edge Painting", region: "USA", category: "Modern Abstract", description: "Abrupt, crisp transitions between color areas defined by clean geometric lines." },
  { name: "Color Field Painting", region: "USA", category: "Modern Abstract", description: "Large flat expanses of solid unmodulated color inviting quiet contemplation." },
  { name: "Action Painting (Gestural Abstract)", region: "USA", category: "Modern Abstract", description: "Spontaneous dripping, splashing, and energetic paint application directly onto canvas." },
  { name: "Digital Painting", region: "Worldwide", category: "Digital Medium", description: "Raster/vector painting using digital tablets, stylus tools, and software brushes." },
  { name: "Mixed Media Collage", region: "Worldwide", category: "Contemporary", description: "Combining paint with found objects, paper scraps, textiles, and medium gels." },
  { name: "Luminism", region: "USA", category: "19th C Landscape", description: "Smooth, invisible brushwork capturing radiant, tranquil atmospheric light over water." },
  { name: "Tenebrism", region: "Europe", category: "Baroque Technique", description: "Extreme contrast where darkness is a dominant feature with intense spotlighting." },
  { name: "Grisaille", region: "Europe", category: "Monochrome Technique", description: "Painting executed entirely in shades of grey to imitate sculpture or relief work." },
  { name: "Sanguine Drawing / Painting", region: "Europe", category: "Classical Medium", description: "Art created with reddish-brown natural iron oxide chalks and wet washes." },
  { name: "Stenciling / Pochoir", region: "Worldwide", category: "Print/Paint Technique", description: "Applying color through cut-out stencil templates for uniform graphic patterns." },
  { name: "Body Painting", region: "Worldwide", category: "Body Art", description: "Temporary pigments applied directly onto human skin for ritual, performance, or art." },
];
